language: cpp
compiler: g++-5
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lua5.1
            - liblua5.1-dev
      install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
      script:
        - ci/test_all.sh -DLUA_INCLUDE_DIR="/usr/include/lua5.1" -DLUA_LIBRARY="/usr/lib/x86_64-linux-gnu/liblua5.1.so"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lua5.2
            - liblua5.2-dev
      install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
      script:
        - ci/test_all.sh -DLUA_INCLUDE_DIR="/usr/include/lua5.2" -DLUA_LIBRARY="/usr/lib/x86_64-linux-gnu/liblua5.2.so"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - sudo add-apt-repository -y "deb http://ppa.launchpad.net/grilo-team/travis/ubuntu trusty main"
        - sudo add-apt-repository -y "deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu trusty main"
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq --force-yes lua5.3 liblua5.3-dev
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
        - sudo update-alternatives --install /usr/bin/lua lua /usr/bin/lua5.3 1
      script:
        - ci/test_all.sh -DLUA_INCLUDE_DIR="/usr/include/lua5.3" -DLUA_LIBRARY="/usr/lib/x86_64-linux-gnu/liblua5.3.so"

    - os: osx
      compiler: clang
      osx_image: xcode8.3
      before_install:
        - brew update
      install:
        - brew install lua@5.1
      script:
        - SOL2_OS_DETECTION_WORKAROUND=1 ci/test_all.sh
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      before_install:
        - brew update
      install:
        - brew install lua@5.2
      script:
        - ci/test_all.sh
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      before_install:
        - brew update
      install:
        - brew install lua@5.3
      script:
        - LUA_BIN=lua5.3 ci/test_all.sh
