language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: g++-5
      env: LUA=lua5.1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 30

    - compiler: clang
      env: LUA=lua5.1
      os: osx
      osx_image: xcode8.3
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua
    - compiler: g++-5
      env: LUA=lua5.2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 30

    - compiler: clang
      env: LUA=lua5.2
      os: osx
      osx_image: xcode8.3
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua
    - compiler: g++-5
      env: LUA=lua5.3
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 30

    - compiler: clang
      env: LUA=lua5.3
      os: osx
      osx_image: xcode8.3
      install:
        - ci/test_all.sh $LUA $TRAVIS_BUILD_DIR/lua

script:
  - ci/test_all.sh -DLUA_INCLUDE_DIR="$TRAVIS_BUILD_DIR/lua/include" -DLUA_LIBRARY="$TRAVIS_BUILD_DIR/lua/lib/liblua.so"
